SELECT UCID, CARD_TYPE, INCOME_CLASS, HOUSEHOLD_INCOME_SUBRANGE,DERIVED_RACE,
				BIRTH_DATE,AGE_YEARS,GENDER,INFO_CHANGED_DATE,CREATED_DATE
		FROM (
			SELECT UCID, CARD_TYPE, INCOME_CLASS, HOUSEHOLD_INCOME_SUBRANGE,DERIVED_RACE,
					BIRTH_DATE,AGE_DAYS,AGE_YEARS,GENDER,INFO_CHANGED_DATE,CREATED_DATE
			FROM (
				SELECT * FROM {{ ref('wns_nm_DD_UCID_HHI_DEMO_TEMP3') }}   WHERE UCID IN ( 
					SELECT UCID FROM (
						SELECT UCID, COUNT(*)AS CNT
						FROM {{ ref('wns_nm_DD_UCID_HHI_DEMO_TEMP3') }}
						GROUP BY 1)
					WHERE CNT=1) -- AND ( INCOME_CLASS IS NOT NULL )
				ORDER BY UCID,HOUSEHOLD_INCOME_SUBRANGE,DERIVED_RACE,BIRTH_DATE,
						AGE_DAYS,AGE_YEARS,GENDER,INFO_CHANGED_DATE,CREATED_DATE)
				UNION
				SELECT UCID, CARD_TYPE, INCOME_CLASS, HOUSEHOLD_INCOME_SUBRANGE,DERIVED_RACE,
						BIRTH_DATE,AGE_DAYS,AGE_YEARS,GENDER,INFO_CHANGED_DATE,CREATED_DATE
				FROM (
					SELECT UCID, CARD_TYPE, INCOME_CLASS, HOUSEHOLD_INCOME_SUBRANGE,DERIVED_RACE,
							BIRTH_DATE,AGE_DAYS,AGE_YEARS,GENDER,INFO_CHANGED_DATE,CREATED_DATE,
					ROW_NUMBER() OVER(PARTITION BY UCID ORDER BY INFO_CHANGED_DATE DESC,DERIVED_RACE DESC,AGE_DAYS ASC,GENDER ASC) AS RN
					FROM (
						SELECT * FROM {{ ref('wns_nm_DD_UCID_HHI_DEMO_TEMP3') }}
						WHERE UCID IN (
							SELECT UCID FROM (
								SELECT UCID, COUNT(*)AS CNT
								FROM {{ ref('wns_nm_DD_UCID_HHI_DEMO_TEMP3') }}
								GROUP BY 1)
							WHERE CNT>1) -- AND ( INCOME_CLASS IS NOT NULL )
						AND (INCOME_CLASS <>-1 AND INCOME_CLASS<>' ' AND INCOME_CLASS IS NOT NULL )
						ORDER BY UCID,HOUSEHOLD_INCOME_SUBRANGE,DERIVED_RACE,BIRTH_DATE,
								AGE_DAYS,AGE_YEARS,GENDER,INFO_CHANGED_DATE,CREATED_DATE))
				WHERE RN=1);
-- Execution time: 18.21s
