CREATE TABLE wns_nm_DD_DEMOGOG_STAGING AS (
	SELECT SUBSCRIBER_KEY,CUSTOMER_NO,CARD_ID,GENDER,TRUNC(DOB) AS DOB,
			(CURRENT_DATE-TRUNC(DOB)) AS AGE,
			(CURRENT_DATE-TRUNC(DOB))/365 AS AGE_YEARS
	FROM (
		SELECT SUBSCRIBER_KEY,CUSTOMER_NO,CARD_ID,
				CASE WHEN GEND_IND BETWEEN 0000 AND 4999 THEN 'F'
					 WHEN GEND_IND BETWEEN 5000 AND 9999 THEN 'M'
					 ELSE 'UNKNOWN' END AS GENDER,
				CASE WHEN DATE_PART_YEAR(BIRTH_DATE) BETWEEN 2000 AND 2019 THEN BIRTH_DATE
					 WHEN DATE_PART_YEAR(BIRTH_DATE)BETWEEN 1900 AND 1919 THEN  DATEADD(YEAR,100,BIRTH_DATE)
					 WHEN DATE_PART_YEAR(BIRTH_DATE) BETWEEN 1920 AND 1999 THEN BIRTH_DATE
					 ELSE DATEADD(YEAR,-100,BIRTH_DATE) END AS DOB
		FROM (
			SELECT SUBSCRIBER_KEY,CUSTOMER_NO,CARD_ID,TRUNC(TO_DATE(LEFT(CARD_ID,6),'YYMMDD'))AS BIRTH_DATE,SUBSTRING(CARD_ID,7,4) AS GEND_IND
			FROM (
				SELECT SUBSCRIBER_KEY,CUSTOMER_NO,MAX(CARD_ID) AS CARD_ID
				FROM (
					SELECT SUBSCRIBER_KEY ,CUSTOMER_NO , CARDHOLDER_IDENTITY_NO AS CARD_ID
					FROM DEVELOPMENT.DIM_CUSTOMER_CARD_MAPPING
					WHERE CARD_ID IS NOT NULL AND CARD_ID <> -1)
					GROUP BY 1,2))));