CREATE TABLE wns_nm_DD_UCID_HHI_INFO AS (
	SELECT A.*, B.EA_CODE,INCOME_CLASS,HOUSEHOLD_INCOME_SUBRANGE
	FROM (
		SELECT UCID,SUBSCRIBER_KEY,CUSTOMER_NO,CARD_TYPE
		FROM {{ ref('wns_nm_DD_TT_UCID_REFTABLE') }}
		GROUP BY 1,2,3,4) A
	LEFT JOIN (
		SELECT CUSTOMER_NO, EA_CODE
		FROM ANALYTICS.FND_CUSTOMER
		GROUP BY 1,2) B
	ON A.CUSTOMER_NO=B.CUSTOMER_NO
	LEFT JOIN (
		SELECT EA_CODE,RACE_CODE,INCOME_CLASS,HOUSEHOLD_INCOME_SUBRANGE,AVERAGE_ADULT_AGE
		FROM DEVELOPMENT.FND_LST_EA_CODES
		GROUP BY 1,2,3,4,5) C
	ON B.EA_CODE=C.EA_CODE);
-- Execution time: 16.48s